### ISSUE TITLE
Unexpected handling of unicode when combining files

### ISSUE THREAD

**Issue by katettudelft** [PasaOpasen/toml-union#1]
Hello,

I saw some unexpected behaviour when combining two files together via your docker image.

Here's an example:

File 1:
```toml
[aws]
symbol = "  "
```

File 2:
```toml
[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
```

I'd expected a result like this:

```toml
[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = "  "
```

But actually got:

```toml
[aws]
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"
symbol = "\ue33d  "
```

As you can see, `"  "` is converted to `"\ue33d  "`. Any ideas on what might be causing this?

For context, I'm trying to merge two [Starship Presets](https://starship.rs/presets/) together, which make use of the unicode glyphs from [Nerd Fonts](https://www.nerdfonts.com).

The preset files are a lot longer than my examples, which is why I was so pleased to see your repo! It'll be a hell of a timesaver. :)
